// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1jUIQXd1wHyxMd4yaLBuY7l-K0Py7o4M',
    appId: '1:847070903313:web:6d0429d2e0f7b1eba8c5b0',
    messagingSenderId: '847070903313',
    projectId: 'groceryglide-89876',
    authDomain: 'groceryglide-89876.firebaseapp.com',
    storageBucket: 'groceryglide-89876.firebasestorage.app',
    measurementId: 'G-DEQV8T23YP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDrMozOMtVbSO6HitvPXkMDv9EGOS68SI',
    appId: '1:847070903313:android:e411d41acad78f1da8c5b0',
    messagingSenderId: '847070903313',
    projectId: 'groceryglide-89876',
    storageBucket: 'groceryglide-89876.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNU3mMSuSQSklYV8RKm0QpjVIPRTTNekw',
    appId: '1:847070903313:ios:a063849932ae3483a8c5b0',
    messagingSenderId: '847070903313',
    projectId: 'groceryglide-89876',
    storageBucket: 'groceryglide-89876.firebasestorage.app',
    iosBundleId: 'com.bvbyco.groceryGlide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNU3mMSuSQSklYV8RKm0QpjVIPRTTNekw',
    appId: '1:847070903313:ios:a063849932ae3483a8c5b0',
    messagingSenderId: '847070903313',
    projectId: 'groceryglide-89876',
    storageBucket: 'groceryglide-89876.firebasestorage.app',
    iosBundleId: 'com.bvbyco.groceryGlide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1jUIQXd1wHyxMd4yaLBuY7l-K0Py7o4M',
    appId: '1:847070903313:web:7a6ae72e388ddf2da8c5b0',
    messagingSenderId: '847070903313',
    projectId: 'groceryglide-89876',
    authDomain: 'groceryglide-89876.firebaseapp.com',
    storageBucket: 'groceryglide-89876.firebasestorage.app',
    measurementId: 'G-8ERQGQ9J7V',
  );
}
